### ISSUE TITLE
mycosnp-bwa-pre-process installation fails, unable to clone apps

### ISSUE THREAD

**Issue by tgallagh** [CDCgov/mycosnp-bwa-pre-process#1]
Hi John,

Thank you for making this awesome workflow for fungal WGS! I'm excited to try it out! 

We (Utah Public Health Lab) were able to successfully install geneflow and the 1st and 3rd workflows. However, I am unable to clone the apps for the 2nd workflow (mycosnp-bwa-pre-process). Could it be an authentication or permissions issue with non-cdc users access to the apps hosted on https://git.biotech.cdc.gov/?

**More details:**

Os: CentOS Linux 7
Python 3.8.3

**Input commands:**
$ gf install-workflow --make-apps -g https://github.com/CDCgov/mycosnp-bwa-pre-process mycosnp-bwa-pre-process

**Output:**
2021-03-10 07:57:39 INFO GeneFlow 2.2.1
2021-03-10 07:57:39 INFO app: concat-fastq-lanes:https://git.biotech.cdc.gov/geneflow-apps/concat-fastq-lanes-gf2.git [0.2]
2021-03-10 07:57:40 ERROR cannot clone app git repo: https://git.biotech.cdc.gov/geneflow-apps/concat-fastq-lanes-gf2.git [Cmd('git') failed due to: exit code(128)
cmdline: git clone --branch=0.2 --config=http.sslVerify=false -v https://git.biotech.cdc.gov/geneflow-apps/concat-fastq-lanes-gf2.git /home/tgallagher/mycosnp/mycosnp-bwa-pre-process/apps/concat-fastq-lanes
stderr: 'fatal: unable to access 'https://git.biotech.cdc.gov/geneflow-apps/concat-fastq-lanes-gf2.git/': Could not resolve host: git.biotech.cdc.gov; Unknown error
']
2021-03-10 07:57:40 ERROR cannot clone app to /home/tgallagher/mycosnp/mycosnp-bwa-pre-process/apps/concat-fastq-lanes
2021-03-10 07:57:40 ERROR cannot install workflow apps

Thanks!
Tara

**Comment by jhphan** [comment]
It looks like I forgot to update one of the URLs. git.biotech.cdc.gov is an internal CDC URL. I'll let you know when it's updated.

**Comment by jhphan** [comment]
Hi Tara, I've updated all of the app URLs in the workflow definition. Please try again and let me know if there are still any issues. Thanks!

**Comment by tgallagh** [comment]
Hi John, sorry it took me so long to get back you. It worked, thank you for the fix!
